# Generated by Django 4.2.1 on 2023-06-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="transaction",
            managers=[],
        ),
    ]
