# Generated by Django 4.2.1 on 2023-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_account_managers_alter_transaction_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
