# Generated by Django 4.2.1 on 2023-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_account_branch_code_account_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Deposit", "Deposit"),
                    ("Withdrawal", "Withdrawal"),
                    ("Transfer", "Transfer"),
                ],
                default="Deposit",
                max_length=20,
            ),
        ),
    ]
