# Generated by Django 4.2.1 on 2023-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_transaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="answer_digest",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="security_question",
            field=models.CharField(
                choices=[
                    (
                        "What is your mother's maiden name?",
                        "What is your mother's maiden name?",
                    ),
                    (
                        "What is your best friend's name?",
                        "What is your best friend's name?",
                    ),
                    ("What is your favorite color?", "What is your favorite color?"),
                    ("What is your favorite movie?", "What is your favorite movie?"),
                    ("What is your favorite food?", "What is your favorite food?"),
                    ("What is your favorite sport?", "What is your favorite sport?"),
                    ("What is your favorite book?", "What is your favorite book?"),
                    ("What is your favorite animal?", "What is your favorite animal?"),
                    (
                        "What is your favorite TV show?",
                        "What is your favorite TV show?",
                    ),
                    ("What is your favorite band?", "What is your favorite band?"),
                    (
                        "What is your favorite musician?",
                        "What is your favorite musician?",
                    ),
                    ("What is your favorite actor?", "What is your favorite actor?"),
                    ("What is your favorite game?", "What is your favorite game?"),
                    (
                        "What is your favorite TV show?",
                        "What is your favorite TV show?",
                    ),
                    (
                        "What is your favorite TV show?",
                        "What is your favorite TV show?",
                    ),
                    (
                        "What is your favorite actress?",
                        "What is your favorite actress?",
                    ),
                    ("What is your favorite game?", "What is your favorite game?"),
                    (
                        "What is your favorite TV genre?",
                        "What is your favorite TV genre?",
                    ),
                ],
                default="What is your mother's maiden name?",
                max_length=100,
            ),
        ),
    ]
