# Generated by Django 4.2.1 on 2023-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_account_answer_digest_account_security_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="account",
            name="answer_digest",
            field=models.CharField(
                blank=True,
                help_text="The answer will be saved in the form of hash digest so no one even us can see the real answer",
                max_length=100,
                null=True,
                verbose_name="Answer",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
